#!/bin/bash
# ============================================================
# Script 5: Open Source Manifesto Generator
# Author: [Krishna Thakkar] | Registration: [24MEI10114]
# Course: Open Source Software | Chosen Software: Git
# Description: Asks the user three questions interactively,
#              then generates and saves a personalised open
#              source philosophy manifesto to a .txt file.
# ============================================================

# --- Aliases concept demonstrated via comments ---
# In real shell usage, aliases are shortcuts, for example:
#   alias today='date +%d\ %B\ %Y'
#   alias myname='echo [Your Name]'
# Below, we store reusable values in variables to achieve
# the same effect as aliases in this script context.

echo "========================================================"
echo "       OPEN SOURCE MANIFESTO GENERATOR                 "
echo "========================================================"
echo ""
echo "  Answer three questions to generate your personal"
echo "  open-source philosophy manifesto."
echo ""
echo "========================================================"
echo ""

# --- read: accept interactive input from the user ---
read -p "  1. Name one open-source tool you use every day: " TOOL
echo ""
read -p "  2. In one word, what does 'freedom' mean to you? " FREEDOM
echo ""
read -p "  3. Name one thing you would build and share freely: " BUILD
echo ""

echo "  Generating your manifesto..."
echo ""

# --- Get current date using command substitution ---
DATE=$(date '+%d %B %Y')

# --- Get current username for the output filename ---
USERNAME=$(whoami)

# --- String concatenation: combine strings to form the filename ---
OUTPUT="manifesto_${USERNAME}.txt"

# --- Write manifesto to file ---
# First line uses > to create/overwrite the file
# All subsequent lines use >> to append to the file

echo "========================================================" > "$OUTPUT"
echo "         MY OPEN SOURCE MANIFESTO                      " >> "$OUTPUT"
echo "========================================================" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "Date   : $DATE" >> "$OUTPUT"
echo "Author : $USERNAME" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "--------------------------------------------------------" >> "$OUTPUT"
echo "" >> "$OUTPUT"

# --- String concatenation: embed $TOOL, $FREEDOM, $BUILD into paragraph ---
echo "Every day, I rely on $TOOL -- a piece of software that" >> "$OUTPUT"
echo "someone built, shared, and gifted to the world without" >> "$OUTPUT"
echo "asking for anything in return. To me, open source is" >> "$OUTPUT"
echo "about $FREEDOM. When knowledge is locked away, progress" >> "$OUTPUT"
echo "slows. When source code is hidden, trust is impossible." >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "One day, I want to build $BUILD -- and when I do, I" >> "$OUTPUT"
echo "will share it openly, because I know that the best" >> "$OUTPUT"
echo "software is shaped by many minds and made stronger by" >> "$OUTPUT"
echo "the very act of being shared." >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "I stand on the shoulders of those who came before me." >> "$OUTPUT"
echo "It is my turn to hold someone else up." >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "--------------------------------------------------------" >> "$OUTPUT"
echo "  Tool I use    : $TOOL" >> "$OUTPUT"
echo "  Freedom means : $FREEDOM" >> "$OUTPUT"
echo "  I will build  : $BUILD" >> "$OUTPUT"
echo "--------------------------------------------------------" >> "$OUTPUT"
echo "  Generated by Open Source Manifesto Generator" >> "$OUTPUT"
echo "  VITyarthi | Open Source Software Course" >> "$OUTPUT"
echo "========================================================" >> "$OUTPUT"

# --- Confirm file was saved ---
echo "========================================================"
echo "  Manifesto saved to: $OUTPUT"
echo "========================================================"
echo ""

# --- Display the manifesto using cat ---
cat "$OUTPUT"
